ALTER TABLE counter DROP COLUMN id;
ALTER TABLE counter ALTER COLUMN key TYPE TEXT;

ALTER TABLE hash ALTER COLUMN id TYPE BIGINT;
ALTER TABLE hash ALTER COLUMN key TYPE TEXT;
ALTER TABLE hash ALTER COLUMN field TYPE TEXT;

ALTER TABLE job ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE job_id_seq AS BIGINT;
ALTER TABLE job ALTER COLUMN stateid TYPE BIGINT;
ALTER TABLE job ALTER COLUMN statename TYPE TEXT;

ALTER TABLE state ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE state_id_seq AS BIGINT;
ALTER TABLE state ALTER COLUMN jobid TYPE BIGINT;
ALTER TABLE state ALTER COLUMN name TYPE TEXT;
ALTER TABLE state ALTER COLUMN reason TYPE TEXT;

ALTER TABLE jobparameter ALTER COLUMN id TYPE BIGINT;
ALTER TABLE jobparameter ALTER COLUMN name TYPE TEXT;
ALTER SEQUENCE jobparameter_id_seq AS BIGINT;
ALTER TABLE jobparameter ALTER COLUMN jobid TYPE BIGINT;

ALTER TABLE jobqueue ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE jobqueue_id_seq AS BIGINT;
ALTER TABLE jobqueue ALTER COLUMN jobid TYPE BIGINT;

ALTER TABLE lock ALTER COLUMN resource TYPE TEXT;

ALTER TABLE list ALTER COLUMN id TYPE BIGINT;
ALTER TABLE list ALTER COLUMN key TYPE TEXT;
ALTER SEQUENCE list_id_seq AS BIGINT;
CREATE INDEX ix_hangfire_list_key ON list (key);

ALTER TABLE set DROP COLUMN id;
ALTER TABLE set ALTER COLUMN key TYPE TEXT;
ALTER TABLE set DROP CONSTRAINT set_key_value_key;
ALTER TABLE set ADD PRIMARY KEY (key, value);
