ALTER TABLE counter ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE counter_id_seq AS BIGINT; 

ALTER TABLE hash ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE hash_id_seq AS BIGINT;

ALTER TABLE job ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE job_id_seq AS BIGINT;
ALTER TABLE job ALTER COLUMN stateid TYPE BIGINT;

ALTER TABLE state ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE state_id_seq AS BIGINT;
ALTER TABLE state ALTER COLUMN jobid TYPE BIGINT;

ALTER TABLE jobparameter ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE jobparameter_id_seq AS BIGINT;
ALTER TABLE jobparameter ALTER COLUMN jobid TYPE BIGINT;

ALTER TABLE jobqueue ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE jobqueue_id_seq AS BIGINT;
ALTER TABLE jobqueue ALTER COLUMN jobid TYPE BIGINT;
--CREATE INDEX jobqueue_queue ON jobqueue (queue);
--CREATE INDEX jobqueue_fetchedat ON jobqueue (fetchedat NULLS FIRST);

ALTER TABLE list ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE list_id_seq AS BIGINT;

ALTER TABLE set ALTER COLUMN id TYPE BIGINT;
ALTER SEQUENCE set_id_seq AS BIGINT;
